### ISSUE TITLE
Add listen deletion

### ISSUE THREAD

**Issue by Cwavs** [metabrainz/pylistenbrainz#20]
Seen as listens can be added and gotten, it would be nice to also have the option to delete them!

**Comment by sambhavnoobcoder** [comment]
hey there @Cwavs ,@musicbrainz, I am beginner to open source looking to contribute to this repo . could you point me in the right direction , such as an issue from where I could start contributing ?thanks .

**Comment by seanbreckenridge** [comment]
Seems like this was added a few weeks ago, just not documented/released yet

https://github.com/metabrainz/pylistenbrainz/commit/e3631dcbe887c21be1adb795553ba28d0b425786

If you install from git:

```
pip install git+https://github.com/metabrainz/pylistenbrainz
```

should be able to use it.

Seems like you pass it a listen but the only things used internally are the `listened_at` and `recording_msid`, so I just set that to a dummy value for the `listened_at` as shown in the docs:

https://listenbrainz.readthedocs.io/en/latest/users/api/core.html#post--1-delete-listen

Then pass it the `recording_msid` and seems to not error on me:

```python
def delete_listen(msid: str, token: str) -> None:
    client = pylistenbrainz.ListenBrainz()
    client.set_auth_token(token)
    listen = pylistenbrainz.Listen(
        track_name="", artist_name="", listened_at=1, recording_msid=msid
    )
    # could throw pylistenbrainz.errors.ListenBrainzAPIException
    client.delete_listen(listen)
```

have a full cli script up here:

https://github.com/seanbreckenridge/listenbrainz_export/blob/master/scripts/listenbrainz-unscrobble

**Comment by Cwavs** [comment]
Ah great, I'll close this issue then, it seems pretty straight forward to use.
